### PR TITLE
Script to Generate Initial Poem Data

### PR DESCRIPTION
**Pull request by thehabes**

### CODE REVIEW

**Review by cubap — CHANGES_REQUESTED** [review]
I don't mind this code and the script is good, but I do not want to ship this script that hammers RERUM and duplicates our data.

**Comment by thehabes** [comment]
Yes, essentially like you said earlier we need to orphan this as a "just for us" thing.

**Comment by thehabes** [comment]
> I don't mind this code and the script is good, but I do not want to ship this script that hammers RERUM and duplicates our data.

Yes, essentially like you said earlier we need to orphan this as a "just for us" thing.

**Comment by thehabes** [comment]
We are not absorbing these scripts into main.  We are keeping it on its own branch, just for us.

**Pull request closed without merging**
